apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: tech-assignment
spec:
  selector:
    app: kibana
  ports:
    - name: ui
      port: 5601
      targetPort: 5601
      protocol: TCP
