apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: tech-assignment
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - elasticsearch
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl
          image: busybox:1.31.1
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9300
              name: discovery
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: conf
              mountPath: /elasticsearch/config/conf
              readOnly: true
          env:
            - name: NUMBER_OF_MASTERS
              value: "3"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
          resources:
            limits:
              memory: 3Gi
            requests:
              memory: 3Gi
      volumes:
        - name: conf
          configMap:
            name: elasticsearch-config
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
